
LAST = [
	'Albach', 'Alcantar', 'Alder', 'Alegre'
	'Alers', 'Alessandro', 'Alken', 'Amano'
	'Arleth', 'Armiger', 'Askvig', 'Avant'
	'Avison', 'Bancroft', 'Barick', 'Barrick'
	'Basset', 'Bechtel', 'Belmont', 'Bentzen'
	'Berrett', 'Beyett', 'Blackford', 'Bowdoin'
	'Breton', 'Bucanan', 'Buccheri', 'Burcham'
	'Byrn', 'Calder', 'Caldera', 'Callahan'
	'Cantos', 'Carrick', 'Carthen', 'Castiglione'
	'Castillon', 'Catlow', 'Cayne', 'Cedeno'
	'Centrich', 'Chalet', 'Corwin', 'Croyle'
	'Dering', 'Desai', 'Dewitt', 'Dilucca'
	'Diseth', 'Dituri', 'Dowe', 'Drayton'
	'Ducote', 'Engstrom', 'Erikson', 'Esperon'
	'Faulknen', 'Flanigan', 'Forgrave', 'Foxwell'
	'Frakes', 'Galven', 'Gammon', 'Ghelfi'
	'Girbach', 'Graydon', 'Greaves', 'Grippen'
	'Gulsvig', 'Hames', 'Hammacher', 'Harcrow'
	'Hartjen', 'Haught', 'Helsing', 'Hewett'
	'Hohstadt', 'Holbach', 'Holtz', 'Hyden'
	'Hyland', 'Iavarone', 'Irani', 'Jackstadt'
	'Jadin', 'Jaenke', 'Jammer', 'Jann'
	'Kader', 'Kampf', 'Kehoe', 'Kerensky'
	'Kiani', 'Kingston', 'Kinnear', 'Kinton'
	'Kniffin', 'Koerner', 'Konicek', 'Laux'
	'Lavanchy', 'Lavigne', 'Leath', 'Lien'
	'Linkovich', 'Llewellyn', 'Locke', 'Lockley'
	'Macbeth', 'Machesky', 'Madi', 'Madigan'
	'Maille', 'Malik', 'Markell', 'Mattix'
	'McLaren', 'McRaven', 'Melchor', 'Mika'
	'Moneaux', 'Morgan', 'Nakada', 'Nesheim'
	'Nicolau', 'Nylund', 'Nyseth', 'O\'Heron'
	'Ocano', 'Paulsen', 'Phillips', 'Quintan'
	'Racine', 'Rackham', 'Raschke', 'Reade'
	'Rhyne', 'Riordan', 'Rocheford', 'Rosek'
	'Ryant', 'Ryen', 'Sabine', 'Sanghvi'
	'Sarratt', 'Scofield', 'Severt', 'Sharpey'
	'Simril', 'Sladek', 'Slayton', 'Smith'
	'Solari', 'Sonoda', 'Stasny', 'Steiger'
	'Steward', 'Stoyer', 'Takach', 'Tameron'
	'Thoran', 'Tian', 'Tindal', 'Toten'
	'Tower', 'Tronstad', 'Tyrrell', 'Vangelos'
	'Vanlaere', 'Vanlith', 'Vasser', 'Veillon'
	'Verrill', 'Vilchis', 'Voight', 'Volante'
	'Wakeman', 'Waring', 'Warwick', 'Watanabe'
	'Watrous', 'Wescott', 'Wethern', 'Weyer'
	'Wildner', 'Winslett', 'Woldt', 'Wyke'
	'Wynn', 'Wynter', 'Wyrick', 'Wyse'
	'Yueh', 'Zahra', 'Zavaleta', 'Zechiel'
	'Zemke', 'Zephyr'
]

FIRST = [
	'Alden', 'Alec', 'Anton', 'Arden'
	'Arlen', 'Armand', 'Arron', 'Augustus'
	'Avery', 'Benedict', 'Bennett', 'Branden'
	'Brendon', 'Britt', 'Broderick', 'Carter'
	'Chadwick', 'Chas', 'Chet', 'Colby'
	'Cole', 'Cordell', 'Dalton', 'Damien'
	'Dante', 'Darell', 'Darius', 'Darron'
	'Darwin', 'Dewitt', 'Diego', 'Dillon'
	'Dirk', 'Domenic', 'Donovan', 'Dorian'
	'Dorsey', 'Edison', 'Elden', 'Elvin'
	'Erich', 'Galen', 'Garret', 'Gaston'
	'Gavin', 'German', 'Graham', 'Hal'
	'Hank', 'Harlan', 'Hayden', 'Herschel'
	'Hoyt', 'Hunter', 'Isaias', 'Issac'
	'Jacinto', 'Jarred', 'Jonas', 'Kendrick'
	'Keneth', 'Kennith', 'Keven', 'Leif'
	'Lenard', 'Lincoln', 'Linwood', 'Lucius'
	'Lynwood', 'Malcolm', 'Malik', 'Maxwell'
	'McKinley', 'Merlin', 'Merrill', 'Michal'
	'Monty', 'Newton', 'Nolan', 'Porter'
	'Quinton', 'Raphael', 'Reid', 'Rory'
	'Scotty', 'Shad', 'Stanton', 'Stefan'
	'Thaddeus', 'Tobias', 'Trenton', 'Vance'
	'Walker', 'Walton', 'Weldon', 'Wes'
	'Weston', 'Willian', 'Winford', 'Wyatt'
]

module.exports = ->
	fi = Math.floor Math.random() * FIRST.length
	li = Math.floor Math.random() * LAST.length
	return "#{FIRST[fi]} #{LAST[li]}"
